#!/usr/bin/env bash
# Bash script with minimum commands to automate your fix.
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
